server.port=${PORT:8081}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/static_database}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=1000

spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

app.seed-data=${APP_SEED_DATA:true}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
