SIM_DURATION = 5
EXPLODE_THRESHOLD = 0
NOF_USERS = 30
NOF_WORKERS = 1
NOF_WORKER_SEATS = 6
NOF_PAUSE = 0
P_SERV_MIN = 100
P_SERV_MAX = 100
N_NANO_SECS_PER_MIN = 1000000
MAX_REQUESTS = 1
MINS_PER_DAY = 120
P_PAUSE = 0
