# configuration_file.conf
# This file defines the parameters for execution of the simulation.
# The simulation will run until the programmed duration (SIM_DURATION) is completed or
# the EXPLODE_THRESHOLD is reached by the value of queue for the services at the end of day.

SIM_DURATION = 5
EXPLODE_THRESHOLD = 11
NOF_USERS = 300
NOF_WORKERS = 8
NOF_WORKER_SEATS = 6
NOF_PAUSE = 2
P_SERV_MIN = 30
P_SERV_MAX = 90
N_NANO_SECS_PER_MIN = 10000000
MAX_REQUESTS = 4
MINS_PER_DAY = 480
P_PAUSE = 3