SIM_DURATION = 2
EXPLODE_THRESHOLD = 1000
NOF_USERS = 30
NOF_WORKERS = 8
NOF_WORKER_SEATS = 6
NOF_PAUSE = 2
P_SERV_MIN = 60
P_SERV_MAX = 90
N_NANO_SECS_PER_MIN = 1000000
MAX_REQUESTS = 3
MINS_PER_DAY = 240
P_PAUSE = 3
